### ISSUE TITLE
Setting ES_USERNAME and ES_PASSWORD does nothing

### ISSUE THREAD

**Issue by rlm95** [openzipkin/docker-zipkin#147]
In my docker-compse.yml I try to set ES_USERNAME and ES_PASSWORD. When I go to the zipkin UI I get the following error 
```
ERROR: cannot load service names: response failed: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```

in my docker compose file
```
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
     - "9411:9411"
    environment:
      - KAFKA_ZOOKEEPER=kafka:2181
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
      - ES_USERNAME=username
      - ES_PASSWORD=password
```
