### ISSUE TITLE
[questing] Empty grafana dashboard

### ISSUE THREAD

**Issue by Igor-lkm** [openzipkin/docker-zipkin#219]
Problem: Dashboard 1598 is empty, data  from zipkin is in Prometheus 

Setup: k8s cluster with zipkin, prometheus (helm) and grafana (helm)

I am using `zipkin-transport-http` to send data to zipkin

Dashboard: https://grafana.com/grafana/dashboards/1598

```
gnetId: 1598
revision: 15
```

Zipkin deployment config on k8s:

```
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9411'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: zipkin
          image: 'openzipkin/zipkin:2.15.0'
```

Example response produces by `zipkin:9411/actuator/prometheus`

```
zipkin_collector_messages_total{transport="http",} 223.0
```

Dashboard is empty:

<img width="1622" alt="Screenshot 2019-08-05 at 11 20 42" src="https://user-images.githubusercontent.com/6287367/62453715-2fa56000-b773-11e9-9bbe-38a2584bf60a.png">

Data is in prometheus:

<img width="1625" alt="Screenshot 2019-08-05 at 11 20 58" src="https://user-images.githubusercontent.com/6287367/62453736-39c75e80-b773-11e9-8fe8-e579ea2548d7.png">

### Example: Messages received per transport

Example query from dashboard:

```
sum by(transport)(rate(zipkin_collector_messages_total{job="zipkin",instance=~"$instances"}[$__interval]))
```

And seems i do not have `job="zipkin",instance=~"$instances"`

So this would work:

```
sum by(transport)(rate(zipkin_collector_messages_total{}[5m]))
```

Seems somehow `job` and `instance` are missed 🤔 Maybe I am missing something? 

Thanks for the help!
