### ISSUE TITLE
Docker-compose kafka not working

### ISSUE THREAD

**Issue by asim** [openzipkin/docker-zipkin#85]
Hi there. I'm using openzipkin/zipkin-kafka:1.27.0 and a modified docker-compose file from https://github.com/openzipkin/docker-zipkin/pull/64 but it does not appear to work. Kafka seems to block with any requests sent to it. Can you confirm that the image specified works. Even sending a simple message to kafka on a different topic blocks indefinitely.

**Comment by adriancole** [comment]
It did at one point. I think I made a custom htrace sink. We should be able
to reproduce this.

**Comment by asim** [comment]
Appreciate the quick response. Would be great to be able to reproduce. The compose file is fairly standard.

```
kafka:
  image: openzipkin/zipkin-kafka:1.27.0
  ports:
    - 2181:2181
    - 9092:9092
  expose:
    - 2181
    - 9092
cassandra:
  image: openzipkin/zipkin-cassandra:1.27.0
  ports:
    - 9042:9042
# The collector process is used for legacy zipkin instrumentation, which log via
# scribe. It can also poll kafka, when the KAFKA_ZOOKEEPER variable is set.
collector:
  image: openzipkin/zipkin-collector:1.27.0
  environment:
    - TRANSPORT_TYPE=kafka
    - STORAGE_TYPE=cassandra
  expose:
    # The scribe thrift api listens on this port
    - 9410
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9900
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - kafka
    - cassandra:storage
# The query process services the UI, and also exposes a POST endpoint that
# instrumentation can send trace data to.
query:
  image: openzipkin/zipkin-query:1.27.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=kafka
    - STORAGE_TYPE=cassandra
  expose:
    # The http api is mounted at /api/v1
    - 9411
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9901
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - kafka
    - cassandra:storage
web:
  image: openzipkin/zipkin-web:1.27.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=kafka
  expose:
    # Web UI is mounted at the root, and the http api under /api/v1
    - 8080
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9990
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - kafka
    - query
```
