### ISSUE TITLE
Restore Zipkin Collector

### ISSUE THREAD

**Issue by galderz** [openzipkin/docker-zipkin#95]
@klingerf, why was the the Zipkin Collector was removed ([here](https://github.com/openzipkin/docker-zipkin/commit/371b9ab500f3a4b597f5bd3051969b348d0062fd)) from the `docker-compose` file?. 

This is bad for the out-of-box experience :disappointed: 

After some tried and testing figured out the settings required in the docker compose were:

```
  collector:
    image: openzipkin/zipkin-collector:1.39.3
    environment:
      - TRANSPORT_TYPE=scribe
      - STORAGE_TYPE=cassandra
      # Point the query service at the storage backend
      - CASSANDRA_CONTACT_POINTS=cassandra
    expose:
      # The scribe thrift api listens on this port
      - 9410
      # Admin interface is under the http path /admin
      # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
      - 9900
    ports:
      - 9410:9410
      - 9900:9900
    links:
      - storage
```
